# fly.toml app configuration file generated for westway-v4 on 2024-03-15T13:56:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'westway-v4'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
